import os
from pathlib import Path

def generate_project_structure(output_file="PROJECT_STRUCTURE.md", ignore_dirs=None, ignore_files=None):
    """
    Generate a markdown file documenting the project structure.
    
    Args:
        output_file (str): Name of the output file (default: PROJECT_STRUCTURE.md)
        ignore_dirs (list): Directories to ignore (e.g., ['venv', '.git'])
        ignore_files (list): Files to ignore (e.g., ['.gitignore', '.env'])
    """
    if ignore_dirs is None:
        ignore_dirs = ['.git', '__pycache__', 'venv', 'env', '.idea', '.vscode']
    if ignore_files is None:
        ignore_files = ['.gitignore', '.env', output_file]
    
    project_root = Path.cwd()
    output_path = project_root / output_file
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("# Project Structure\n\n")
        f.write("```\n")
        
        for root, dirs, files in os.walk(project_root):
            # Remove ignored directories
            dirs[:] = [d for d in dirs if d not in ignore_dirs]
            
            # Filter out ignored files
            files = [f for f in files if f not in ignore_files]
            
            level = Path(root).relative_to(project_root).parts
            indent = ' ' * 4 * (len(level) - 1)
            
            # Write directory name
            if level:
                f.write(f"{indent}{level[-1]}/\n")
            else:
                f.write("./\n")
            
            # Write files in directory
            sub_indent = ' ' * 4 * len(level)
            for file in sorted(files):
                f.write(f"{sub_indent}{file}\n")
        
        f.write("```\n")
        f.write("\nGenerated by project_structure_generator.py\n")
    
    print(f"Project structure saved to {output_path}")

if __name__ == "__main__":
    # Customize ignored directories and files as needed
    generate_project_structure(
        ignore_dirs=['venv', '__pycache__', '.git', '.idea'],
        ignore_files=['.gitignore', '.env', '*.pyc']
    )