"""create_saved_searches_table

Revision ID: 4ccec89bf6c0
Revises: a866e0e42ae7
Create Date: 2025-06-09 13:00:06.476333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ccec89bf6c0'
down_revision: Union[str, None] = 'a866e0e42ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='User-defined name for the saved search'),
    sa.Column('search_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSON object of search filters'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_id'), 'saved_searches', ['id'], unique=False)
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.drop_index(op.f('idx_property_embeddings_embedding_hnsw'), table_name='property_embeddings', postgresql_using='hnsw')
    op.drop_constraint(op.f('uq_property_embeddings_property_id'), 'property_embeddings', type_='unique')
    op.alter_column('users', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_property_embeddings_property_id'), 'property_embeddings', ['property_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_property_embeddings_embedding_hnsw'), 'property_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_index(op.f('ix_saved_searches_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
