"""create_initial_database_schema

Revision ID: a866e0e42ae7
Revises: 
Create Date: 2025-06-09 12:40:14.524061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # For postgresql.UUID and postgresql.JSONB
from app.models.property_embedding import Vector # IMPORTANT: For your custom Vector type

# revision identifiers, used by Alembic.
revision: str = 'a866e0e42ae7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # MANUALLY ADDED: Ensure pgvector extension is available
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - START ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True), # Changed to JSONB for PG
    sa.Column('profile_picture_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), # Changed to postgresql.UUID
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')) # Added name
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    
    op.create_table('properties',
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=False), # Changed
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=False),
    sa.Column('num_bedrooms', sa.SmallInteger(), nullable=False),
    sa.Column('num_bathrooms', sa.DECIMAL(precision=3, scale=1), nullable=False),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('rent_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('rent_price_currency', sa.String(length=3), nullable=False),
    sa.Column('rent_price_period', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), # Changed
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_properties_owner_id_users')), # Added name
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties')) # Added name
    )
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_is_published'), 'properties', ['is_published'], unique=False)
    op.create_index(op.f('ix_properties_latitude'), 'properties', ['latitude'], unique=False)
    op.create_index(op.f('ix_properties_longitude'), 'properties', ['longitude'], unique=False)
    op.create_index(op.f('ix_properties_owner_id'), 'properties', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_postal_code'), 'properties', ['postal_code'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_state_province'), 'properties', ['state_province'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    
    op.create_table('property_embeddings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), # Changed & moved id up
    sa.Column('property_id', postgresql.UUID(as_uuid=True), nullable=False), 
    sa.Column('embedding', Vector(), nullable=False), # USED IMPORTED Vector
    sa.Column('source_text_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_embeddings_property_id_properties'), ondelete='CASCADE'), # Added name
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_embeddings')), # Added name
    sa.UniqueConstraint('property_id', name=op.f('uq_property_embeddings_property_id')) # Added name
    )
    op.create_index(op.f('ix_property_embeddings_id'), 'property_embeddings', ['id'], unique=False)
    # The UniqueConstraint on property_id creates a unique index.
    # If the model for property_id also had index=True, Alembic might generate this non-unique one too.
    # For clarity and to rely on the UniqueConstraint for indexing, ensure model has unique=True for property_id.
    op.create_index(op.f('ix_property_embeddings_property_id'), 'property_embeddings', ['property_id'], unique=True) # Changed to unique=True as per model

    # MANUALLY ADDED: pgvector index
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_property_embeddings_embedding_hnsw
        ON property_embeddings
        USING hnsw (embedding vector_cosine_ops);
    """)

    op.create_table('property_images',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), # Changed & moved id up
    sa.Column('property_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('image_url', sa.String(length=512), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_images_property_id_properties'), ondelete='CASCADE'), # Added name
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_images')) # Added name
    )
    op.create_index(op.f('ix_property_images_id'), 'property_images', ['id'], unique=False)
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    # ### commands auto generated by Alembic - END ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - START ###
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_id'), table_name='property_images')
    op.drop_table('property_images')

    # MANUALLY ADDED: Drop pgvector HNSW index first
    op.execute("DROP INDEX IF EXISTS idx_property_embeddings_embedding_hnsw;")
    
    op.drop_index(op.f('ix_property_embeddings_property_id'), table_name='property_embeddings')
    op.drop_index(op.f('ix_property_embeddings_id'), table_name='property_embeddings')
    # op.drop_constraint(op.f('uq_property_embeddings_property_id'), 'property_embeddings', type_='unique') # Usually dropped with table
    op.drop_table('property_embeddings')
    
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_state_province'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_postal_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_owner_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_longitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_latitude'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_published'), table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_table('properties')
    
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # MANUALLY ADDED (OPTIONAL): Drop pgvector extension
    op.execute("DROP EXTENSION IF EXISTS vector;") # Make sure this is really what you want on full rollback
    # ### commands auto generated by Alembic - END ###